# CMake generated Testfile for 
# Source directory: C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD
# Build directory: C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CHOLMOD_int32_double_bcsstk01]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/Debug/cholmod_di_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/bcsstk01.tri")
  set_tests_properties([=[CHOLMOD_int32_double_bcsstk01]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;853;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CHOLMOD_int32_double_bcsstk01]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/Release/cholmod_di_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/bcsstk01.tri")
  set_tests_properties([=[CHOLMOD_int32_double_bcsstk01]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;853;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CHOLMOD_int32_double_bcsstk01]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/MinSizeRel/cholmod_di_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/bcsstk01.tri")
  set_tests_properties([=[CHOLMOD_int32_double_bcsstk01]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;853;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CHOLMOD_int32_double_bcsstk01]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/RelWithDebInfo/cholmod_di_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/bcsstk01.tri")
  set_tests_properties([=[CHOLMOD_int32_double_bcsstk01]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;853;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
else()
  add_test([=[CHOLMOD_int32_double_bcsstk01]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CHOLMOD_int64_double_bcsstk01]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/Debug/cholmod_dl_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/bcsstk01.tri")
  set_tests_properties([=[CHOLMOD_int64_double_bcsstk01]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;855;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CHOLMOD_int64_double_bcsstk01]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/Release/cholmod_dl_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/bcsstk01.tri")
  set_tests_properties([=[CHOLMOD_int64_double_bcsstk01]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;855;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CHOLMOD_int64_double_bcsstk01]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/MinSizeRel/cholmod_dl_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/bcsstk01.tri")
  set_tests_properties([=[CHOLMOD_int64_double_bcsstk01]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;855;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CHOLMOD_int64_double_bcsstk01]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/RelWithDebInfo/cholmod_dl_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/bcsstk01.tri")
  set_tests_properties([=[CHOLMOD_int64_double_bcsstk01]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;855;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
else()
  add_test([=[CHOLMOD_int64_double_bcsstk01]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CHOLMOD_int32_single_bcsstk01]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/Debug/cholmod_si_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/bcsstk01.tri")
  set_tests_properties([=[CHOLMOD_int32_single_bcsstk01]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;857;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CHOLMOD_int32_single_bcsstk01]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/Release/cholmod_si_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/bcsstk01.tri")
  set_tests_properties([=[CHOLMOD_int32_single_bcsstk01]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;857;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CHOLMOD_int32_single_bcsstk01]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/MinSizeRel/cholmod_si_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/bcsstk01.tri")
  set_tests_properties([=[CHOLMOD_int32_single_bcsstk01]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;857;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CHOLMOD_int32_single_bcsstk01]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/RelWithDebInfo/cholmod_si_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/bcsstk01.tri")
  set_tests_properties([=[CHOLMOD_int32_single_bcsstk01]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;857;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
else()
  add_test([=[CHOLMOD_int32_single_bcsstk01]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CHOLMOD_int64_single_bcsstk01]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/Debug/cholmod_sl_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/bcsstk01.tri")
  set_tests_properties([=[CHOLMOD_int64_single_bcsstk01]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;859;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CHOLMOD_int64_single_bcsstk01]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/Release/cholmod_sl_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/bcsstk01.tri")
  set_tests_properties([=[CHOLMOD_int64_single_bcsstk01]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;859;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CHOLMOD_int64_single_bcsstk01]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/MinSizeRel/cholmod_sl_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/bcsstk01.tri")
  set_tests_properties([=[CHOLMOD_int64_single_bcsstk01]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;859;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CHOLMOD_int64_single_bcsstk01]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/RelWithDebInfo/cholmod_sl_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/bcsstk01.tri")
  set_tests_properties([=[CHOLMOD_int64_single_bcsstk01]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;859;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
else()
  add_test([=[CHOLMOD_int64_single_bcsstk01]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CHOLMOD_int32_double_lp_afiro]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/Debug/cholmod_di_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/lp_afiro.tri")
  set_tests_properties([=[CHOLMOD_int32_double_lp_afiro]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;862;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CHOLMOD_int32_double_lp_afiro]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/Release/cholmod_di_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/lp_afiro.tri")
  set_tests_properties([=[CHOLMOD_int32_double_lp_afiro]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;862;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CHOLMOD_int32_double_lp_afiro]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/MinSizeRel/cholmod_di_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/lp_afiro.tri")
  set_tests_properties([=[CHOLMOD_int32_double_lp_afiro]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;862;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CHOLMOD_int32_double_lp_afiro]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/RelWithDebInfo/cholmod_di_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/lp_afiro.tri")
  set_tests_properties([=[CHOLMOD_int32_double_lp_afiro]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;862;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
else()
  add_test([=[CHOLMOD_int32_double_lp_afiro]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CHOLMOD_int64_double_lp_afiro]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/Debug/cholmod_dl_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/lp_afiro.tri")
  set_tests_properties([=[CHOLMOD_int64_double_lp_afiro]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;864;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CHOLMOD_int64_double_lp_afiro]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/Release/cholmod_dl_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/lp_afiro.tri")
  set_tests_properties([=[CHOLMOD_int64_double_lp_afiro]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;864;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CHOLMOD_int64_double_lp_afiro]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/MinSizeRel/cholmod_dl_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/lp_afiro.tri")
  set_tests_properties([=[CHOLMOD_int64_double_lp_afiro]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;864;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CHOLMOD_int64_double_lp_afiro]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/RelWithDebInfo/cholmod_dl_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/lp_afiro.tri")
  set_tests_properties([=[CHOLMOD_int64_double_lp_afiro]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;864;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
else()
  add_test([=[CHOLMOD_int64_double_lp_afiro]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CHOLMOD_int32_single_lp_afiro]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/Debug/cholmod_si_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/lp_afiro.tri")
  set_tests_properties([=[CHOLMOD_int32_single_lp_afiro]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;866;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CHOLMOD_int32_single_lp_afiro]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/Release/cholmod_si_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/lp_afiro.tri")
  set_tests_properties([=[CHOLMOD_int32_single_lp_afiro]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;866;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CHOLMOD_int32_single_lp_afiro]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/MinSizeRel/cholmod_si_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/lp_afiro.tri")
  set_tests_properties([=[CHOLMOD_int32_single_lp_afiro]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;866;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CHOLMOD_int32_single_lp_afiro]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/RelWithDebInfo/cholmod_si_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/lp_afiro.tri")
  set_tests_properties([=[CHOLMOD_int32_single_lp_afiro]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;866;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
else()
  add_test([=[CHOLMOD_int32_single_lp_afiro]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CHOLMOD_int64_single_lp_afiro]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/Debug/cholmod_sl_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/lp_afiro.tri")
  set_tests_properties([=[CHOLMOD_int64_single_lp_afiro]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;868;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CHOLMOD_int64_single_lp_afiro]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/Release/cholmod_sl_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/lp_afiro.tri")
  set_tests_properties([=[CHOLMOD_int64_single_lp_afiro]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;868;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CHOLMOD_int64_single_lp_afiro]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/MinSizeRel/cholmod_sl_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/lp_afiro.tri")
  set_tests_properties([=[CHOLMOD_int64_single_lp_afiro]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;868;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CHOLMOD_int64_single_lp_afiro]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/RelWithDebInfo/cholmod_sl_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/lp_afiro.tri")
  set_tests_properties([=[CHOLMOD_int64_single_lp_afiro]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;868;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
else()
  add_test([=[CHOLMOD_int64_single_lp_afiro]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CHOLMOD_int32_double_can24]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/Debug/cholmod_di_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/can___24.mtx")
  set_tests_properties([=[CHOLMOD_int32_double_can24]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;871;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CHOLMOD_int32_double_can24]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/Release/cholmod_di_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/can___24.mtx")
  set_tests_properties([=[CHOLMOD_int32_double_can24]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;871;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CHOLMOD_int32_double_can24]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/MinSizeRel/cholmod_di_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/can___24.mtx")
  set_tests_properties([=[CHOLMOD_int32_double_can24]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;871;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CHOLMOD_int32_double_can24]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/RelWithDebInfo/cholmod_di_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/can___24.mtx")
  set_tests_properties([=[CHOLMOD_int32_double_can24]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;871;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
else()
  add_test([=[CHOLMOD_int32_double_can24]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CHOLMOD_int64_double_can24]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/Debug/cholmod_dl_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/can___24.mtx")
  set_tests_properties([=[CHOLMOD_int64_double_can24]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;873;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CHOLMOD_int64_double_can24]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/Release/cholmod_dl_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/can___24.mtx")
  set_tests_properties([=[CHOLMOD_int64_double_can24]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;873;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CHOLMOD_int64_double_can24]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/MinSizeRel/cholmod_dl_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/can___24.mtx")
  set_tests_properties([=[CHOLMOD_int64_double_can24]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;873;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CHOLMOD_int64_double_can24]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/RelWithDebInfo/cholmod_dl_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/can___24.mtx")
  set_tests_properties([=[CHOLMOD_int64_double_can24]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;873;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
else()
  add_test([=[CHOLMOD_int64_double_can24]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CHOLMOD_int32_single_can24]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/Debug/cholmod_si_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/can___24.mtx")
  set_tests_properties([=[CHOLMOD_int32_single_can24]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;875;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CHOLMOD_int32_single_can24]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/Release/cholmod_si_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/can___24.mtx")
  set_tests_properties([=[CHOLMOD_int32_single_can24]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;875;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CHOLMOD_int32_single_can24]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/MinSizeRel/cholmod_si_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/can___24.mtx")
  set_tests_properties([=[CHOLMOD_int32_single_can24]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;875;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CHOLMOD_int32_single_can24]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/RelWithDebInfo/cholmod_si_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/can___24.mtx")
  set_tests_properties([=[CHOLMOD_int32_single_can24]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;875;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
else()
  add_test([=[CHOLMOD_int32_single_can24]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CHOLMOD_int64_single_can24]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/Debug/cholmod_sl_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/can___24.mtx")
  set_tests_properties([=[CHOLMOD_int64_single_can24]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;877;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CHOLMOD_int64_single_can24]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/Release/cholmod_sl_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/can___24.mtx")
  set_tests_properties([=[CHOLMOD_int64_single_can24]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;877;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CHOLMOD_int64_single_can24]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/MinSizeRel/cholmod_sl_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/can___24.mtx")
  set_tests_properties([=[CHOLMOD_int64_single_can24]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;877;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CHOLMOD_int64_single_can24]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/RelWithDebInfo/cholmod_sl_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/can___24.mtx")
  set_tests_properties([=[CHOLMOD_int64_single_can24]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;877;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
else()
  add_test([=[CHOLMOD_int64_single_can24]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CHOLMOD_int32_double_complex]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/Debug/cholmod_di_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/c.tri")
  set_tests_properties([=[CHOLMOD_int32_double_complex]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;880;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CHOLMOD_int32_double_complex]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/Release/cholmod_di_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/c.tri")
  set_tests_properties([=[CHOLMOD_int32_double_complex]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;880;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CHOLMOD_int32_double_complex]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/MinSizeRel/cholmod_di_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/c.tri")
  set_tests_properties([=[CHOLMOD_int32_double_complex]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;880;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CHOLMOD_int32_double_complex]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/RelWithDebInfo/cholmod_di_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/c.tri")
  set_tests_properties([=[CHOLMOD_int32_double_complex]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;880;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
else()
  add_test([=[CHOLMOD_int32_double_complex]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CHOLMOD_int64_double_complex]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/Debug/cholmod_dl_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/c.tri")
  set_tests_properties([=[CHOLMOD_int64_double_complex]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;882;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CHOLMOD_int64_double_complex]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/Release/cholmod_dl_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/c.tri")
  set_tests_properties([=[CHOLMOD_int64_double_complex]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;882;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CHOLMOD_int64_double_complex]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/MinSizeRel/cholmod_dl_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/c.tri")
  set_tests_properties([=[CHOLMOD_int64_double_complex]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;882;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CHOLMOD_int64_double_complex]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/RelWithDebInfo/cholmod_dl_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/c.tri")
  set_tests_properties([=[CHOLMOD_int64_double_complex]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;882;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
else()
  add_test([=[CHOLMOD_int64_double_complex]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CHOLMOD_int32_single_complex]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/Debug/cholmod_si_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/c.tri")
  set_tests_properties([=[CHOLMOD_int32_single_complex]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;884;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CHOLMOD_int32_single_complex]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/Release/cholmod_si_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/c.tri")
  set_tests_properties([=[CHOLMOD_int32_single_complex]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;884;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CHOLMOD_int32_single_complex]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/MinSizeRel/cholmod_si_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/c.tri")
  set_tests_properties([=[CHOLMOD_int32_single_complex]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;884;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CHOLMOD_int32_single_complex]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/RelWithDebInfo/cholmod_si_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/c.tri")
  set_tests_properties([=[CHOLMOD_int32_single_complex]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;884;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
else()
  add_test([=[CHOLMOD_int32_single_complex]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CHOLMOD_int64_single_complex]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/Debug/cholmod_sl_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/c.tri")
  set_tests_properties([=[CHOLMOD_int64_single_complex]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;886;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CHOLMOD_int64_single_complex]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/Release/cholmod_sl_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/c.tri")
  set_tests_properties([=[CHOLMOD_int64_single_complex]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;886;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CHOLMOD_int64_single_complex]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/MinSizeRel/cholmod_sl_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/c.tri")
  set_tests_properties([=[CHOLMOD_int64_single_complex]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;886;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CHOLMOD_int64_single_complex]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/RelWithDebInfo/cholmod_sl_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/c.tri")
  set_tests_properties([=[CHOLMOD_int64_single_complex]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;886;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
else()
  add_test([=[CHOLMOD_int64_single_complex]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CHOLMOD_int32_double_supernodal]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/Debug/cholmod_di_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/bcsstk02.tri")
  set_tests_properties([=[CHOLMOD_int32_double_supernodal]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;889;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CHOLMOD_int32_double_supernodal]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/Release/cholmod_di_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/bcsstk02.tri")
  set_tests_properties([=[CHOLMOD_int32_double_supernodal]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;889;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CHOLMOD_int32_double_supernodal]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/MinSizeRel/cholmod_di_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/bcsstk02.tri")
  set_tests_properties([=[CHOLMOD_int32_double_supernodal]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;889;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CHOLMOD_int32_double_supernodal]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/RelWithDebInfo/cholmod_di_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/bcsstk02.tri")
  set_tests_properties([=[CHOLMOD_int32_double_supernodal]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;889;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
else()
  add_test([=[CHOLMOD_int32_double_supernodal]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CHOLMOD_int64_double_supernodal]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/Debug/cholmod_dl_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/bcsstk02.tri")
  set_tests_properties([=[CHOLMOD_int64_double_supernodal]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;891;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CHOLMOD_int64_double_supernodal]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/Release/cholmod_dl_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/bcsstk02.tri")
  set_tests_properties([=[CHOLMOD_int64_double_supernodal]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;891;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CHOLMOD_int64_double_supernodal]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/MinSizeRel/cholmod_dl_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/bcsstk02.tri")
  set_tests_properties([=[CHOLMOD_int64_double_supernodal]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;891;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CHOLMOD_int64_double_supernodal]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/RelWithDebInfo/cholmod_dl_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/bcsstk02.tri")
  set_tests_properties([=[CHOLMOD_int64_double_supernodal]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;891;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
else()
  add_test([=[CHOLMOD_int64_double_supernodal]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CHOLMOD_int32_single_supernodal]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/Debug/cholmod_si_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/bcsstk02.tri")
  set_tests_properties([=[CHOLMOD_int32_single_supernodal]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;893;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CHOLMOD_int32_single_supernodal]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/Release/cholmod_si_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/bcsstk02.tri")
  set_tests_properties([=[CHOLMOD_int32_single_supernodal]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;893;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CHOLMOD_int32_single_supernodal]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/MinSizeRel/cholmod_si_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/bcsstk02.tri")
  set_tests_properties([=[CHOLMOD_int32_single_supernodal]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;893;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CHOLMOD_int32_single_supernodal]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/RelWithDebInfo/cholmod_si_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/bcsstk02.tri")
  set_tests_properties([=[CHOLMOD_int32_single_supernodal]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;893;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
else()
  add_test([=[CHOLMOD_int32_single_supernodal]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CHOLMOD_int64_single_supernodal]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/Debug/cholmod_sl_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/bcsstk02.tri")
  set_tests_properties([=[CHOLMOD_int64_single_supernodal]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;895;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CHOLMOD_int64_single_supernodal]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/Release/cholmod_sl_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/bcsstk02.tri")
  set_tests_properties([=[CHOLMOD_int64_single_supernodal]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;895;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CHOLMOD_int64_single_supernodal]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/MinSizeRel/cholmod_sl_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/bcsstk02.tri")
  set_tests_properties([=[CHOLMOD_int64_single_supernodal]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;895;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CHOLMOD_int64_single_supernodal]=] "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2_config_win_static_seq/CHOLMOD/RelWithDebInfo/cholmod_sl_demo.exe" "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/Demo/Matrix/bcsstk02.tri")
  set_tests_properties([=[CHOLMOD_int64_single_supernodal]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;895;add_test;C:/Users/kummer/Documents/BoSSS-native/SuiteSparse_7.12.2/CHOLMOD/CMakeLists.txt;0;")
else()
  add_test([=[CHOLMOD_int64_single_supernodal]=] NOT_AVAILABLE)
endif()
